// Ordered product spotlight tour steps (client onboarding walkthrough).

export const PRODUCT_TOUR_STEPS = [
  {
    id: 'dashboard_welcome',
    route: 'dashboard',
    targetId: null,
    title: 'Welcome to Alimenta',
    body: 'This is your home base — streak, today’s nutrition, and a daily focus to keep you moving.',
    placement: 'center',
    allowTargetPress: false,
    showSkip: true,
    showBack: false,
    showNext: true,
  },
  {
    id: 'nav_training',
    route: 'dashboard',
    targetId: 'footer-training',
    title: 'Start with training',
    body: 'Log your workouts by day — Alimenta uses them to tune your macros.',
    placement: 'top',
    allowTargetPress: true,
    advanceOn: 'targetPress',
    showSkip: true,
    showBack: true,
    showNext: false,
  },
  {
    id: 'training_build',
    route: 'training',
    targetId: 'training-editor',
    title: 'Log today’s session',
    body: 'Add a workout for today. It saves automatically as you edit.',
    placement: 'bottom',
    forcePlacement: true,
    allowTargetPress: true,
    showSkip: true,
    showBack: true,
    showNext: true,
  },
  {
    id: 'nav_meals',
    route: 'training',
    targetId: 'footer-meals',
    title: 'Now your meals',
    body: 'Generate and manage your weekly meal plan here.',
    placement: 'top',
    allowTargetPress: true,
    advanceOn: 'targetPress',
    showSkip: true,
    showBack: true,
    showNext: false,
  },
  {
    id: 'meals_overview',
    route: 'meals',
    targetId: 'meals-first-slot',
    title: 'Multiple ways to fill a meal',
    body: 'Tap a meal card for these. Use the + button to generate a full day.',
    bodyItems: [
      'Generate with AI',
      'Log what you ate',
      'Meal prep across days',
    ],
    placement: 'bottom',
    allowTargetPress: true,
    advanceOn: 'targetPress',
    showSkip: true,
    showBack: true,
    showNext: false,
  },
  {
    id: 'meals_generate',
    route: 'meals',
    targetId: 'meals-generate-action',
    title: 'Generate your first meal',
    body: 'Pick this to have Alimenta build a meal that fits your macros and training.',
    placement: 'top',
    allowTargetPress: true,
    // Advance only after generateSingleMeal succeeds (see meals.jsx).
    advanceOn: 'mealGenerated',
    showSkip: true,
    showBack: false,
    showNext: true,
  },
  {
    id: 'nav_profile',
    route: 'meals',
    targetId: 'header-avatar',
    title: 'Your profile',
    body: 'Update body metrics here, and switch to the Preferences tab to set likes, dislikes, and cuisines — they steer every meal we generate.',
    placement: 'bottom',
    allowTargetPress: true,
    advanceOn: 'targetPress',
    showSkip: true,
    showBack: true,
    showNext: false,
  },
  {
    id: 'tour_done',
    route: 'profile',
    targetId: null,
    title: "You're set",
    body: 'Replay this anytime from Settings.',
    placement: 'center',
    allowTargetPress: false,
    showSkip: false,
    showBack: false,
    showNext: false,
    // Let the profile screen settle after the avatar tap before showing Done.
    revealDelayMs: 450,
    isLast: true,
  },
];

export const TOUR_ROUTE_MAP = {
  dashboard: '/(app)/dashboard',
  training: '/(app)/training',
  meals: '/(app)/meals',
  profile: '/(app)/profile',
  settings: '/(app)/settings',
};

export const TOUR_VIEW_FROM_SEGMENT = {
  index: 'dashboard',
  dashboard: 'dashboard',
  training: 'training',
  meals: 'meals',
  profile: 'profile',
  settings: 'settings',
  preferences: 'profile',
};
